name: alm
description: A Dart lib, Cool? Try use.
version: 1.0.0
homepage: https://gitee.com/dart-open-source/alm

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.5
  mime: ^0.9.7
  http: ^0.12.2
  image: ^2.1.19
  http_parser: ^3.1.4
